### ISSUE TITLE
Некорректно считается внеучебная работа в выгружаемом Word-файле индивидуального плана

### ISSUE THREAD

**Issue by kimspark** [AlexeyTipunin/TeachersPlan#1]
Не учитывается либо "Научно-методическая деятельность", либо "Воспитательная и профориентационная работа"
Пример:
Кафедра геологии горючих и твердых полезных ископаемых Института геологии, нефтегазодобычи и трубопроводного транспорта, Заборовская Валерия Владимировна
Всего запланировано 542, а в Word-файле насчитывает 522

**Comment by kurle6a** [comment]
а вот и корректно.
